= Howto: Add a custom formView with a fileUpload
Stijn Vanhoof

[abstract]
This how-to will cover the basics of https://across-docs.foreach.be/across-standard-modules/EntityModule/2.1.0.RELEASE/reference/#_creating_an_additional_form_view[creating an additional formView] and managing the
https://across-docs.foreach.be/across-standard-modules/EntityModule/2.1.0.RELEASE/reference/#generic-view[custom view].

A short summary about the topics discussed:

* `Create a fileUpload with validation`
* `Create your own formView on a entity`
* `Register a new property on a formView that is rendered by entityModule`

== Create our file dto class
First we have to create a class that can act as a dto object for our uploaded file.
We can also use this to set our validation annotations if desired.

.FileRequest.java -  Example of dto class for our to be uploaded file
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Setter
@Getter
public class FileRequest {
    @NotNull
    private MultipartFile[] files;
}
----

== Register a new formView on our entity
To create our own formView we have to create a new viewProcessor that extends the `EntityViewProcessorAdapter`.
Just create an empty viewProcessor for now, we will implement it on the next steps.

.FileUploadViewProcessor.java - Empty viewprocessor for now
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Component
public class FileUploadViewProcessor extends EntityViewProcessorAdapter {

}
----

When we have created our new viewProcessor https://across-docs.foreach.be/across-standard-modules/EntityModule/2.1.0.RELEASE/reference/#configuring-views[we can register it on the configuration] of our entity in a `EntityConfigurer`.

NOTE: Find out more about how to configure entity types https://across-docs.foreach.be/across-standard-modules/EntityModule/2.1.0.RELEASE/reference/#_configuring_entity_types[here].

.DummyEntityConfiguration.java - Entity configuration for our dummy entity
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Configuration
@RequiredArgsConstructor
class DummyEntityConfiguration implements EntityConfigurer {
    private final FileUploadViewProcessor fileUploadViewProcessor;

    @Override
    public void configure(EntitiesConfigurationBuilder entities) {
        entities.withType(DummyEntity.class)
            // Attach our custom  formView
            .formView("upload", fvb -> fvb.viewProcessor(fileUploadViewProcessor) # <1>

                // Create a new property files that will represent our file upload element
                .properties(props -> props.property("files") # <2>

                    // Configure a label for the file input field # <3>
                    .displayName("Csv file")

                    // Set the right propertyType
                    .propertyType(MultipartFile[].class) # 

                    /** Set the right viewElementBuilder so entityModule knows how to render
                    * our file upload field. Note that we didn't use .viewElementType that will autodetect
                    * the viewElementBuilder to use.
                    */
                    .viewElementBuilder( # <4>
                        ViewElementMode.CONTROL, BootstrapUiBuilders.file()
                            .controlName("extensions[upload].files")
                    )

                    // We need our new property to be writable
                    .writable(true) # <5>
                )
                // We want to be sure our property is shown on our formView
                .showProperties("files")

                // Remove the default viewProcessor SaveEntityViewProcessor so that only our form get's saved
                // and not the attached entity
                .removeViewProcessor(SaveEntityViewProcessor.class.getName()) # <5>
            );
    }
 }
----

<1> The above code registers a new formView with the name upload and add's our created but not yet implemented viewHelper
to our formView.

<2> Then we register a new property files that we wil use to represent our file upload.
<3> We set a `displayName` we map the property to our `FileRequest` object we created earlier by setting it's `propertyType`.

<4> Across provides a default File control view that we can use by using the `viewElementBuilder`. We want to customize
the control and use the file control provided by BootstrapUiBuilders.file(). The `BootstrapUiBuilders` facade provides a lot of default viewElements that you can use. As you can see in the above code we set the `controlName` (Name attribute) to a specific value and this is required to register the control as an extension.
Read more about extensions https://across-docs.foreach.be/across-standard-modules/EntityModule/2.1.0.RELEASE/reference/#_entityviewcommand[here].
In short extensions is map on the `EntityViewCommand` that we can use to render and validate additional elements.
Later in our newly created `FileUploadViewProcessor` we add the extension but for now we set the name of our element to the right value so the field value get's binded automatically. In the next section you will find out how we actually add the files
property to the extension map.

<5> After we set our newly created property to be writable and show it on our formView there is one more thing we want to do.
By default when we save our formView the corresponding entity (DummyEntity) is also saved by the `SaveEntityViewProcessor` that is registed by default. If we don't want this behavior we can just remove the `viewProcessor`.

== Access the view

Now that our custom `formView` has been registered we can access it by going to the following url admin/entities/dummyEntity?view=upload.
The path is bassicly the path of our `DummyEntity` where we registered our view in. In addition we provide a get paramter
view with the name of our view which is upload.


== Create your own formView on a entity
We need to override 3 methods of the EntityViewProcessorAdapter. In the first method we add
the file upload to the extension map. Remember that we used .controlName("extensions[upload].files") in our entityConfigurer.
We now use the same mapKey to register our files property to the extension map so our rendering & validation & value binding is handled.

NOTE: You can find out more about how entity views work https://across-docs.foreach.be/across-standard-modules/EntityModule/2.1.0.RELEASE/reference/#_how_entity_views_work[here].

.FileUploadViewProcessor.java - Add the extension
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
    @Override
    public void initializeCommandObject(EntityViewRequest entityViewRequest, EntityViewCommand command, WebDataBinder dataBinder) {
        command.addExtension("upload", new FileRequest());
    }
----

We have to make our form multiPart so we look up the form by using our ContainerViewElement and then
we can set set the multiPart encryption on the FormViewElement

.FileUploadViewProcessor.java - Add multiPartForm to our form
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
    @Override
    protected void postRender(EntityViewRequest entityViewRequest, EntityView entityView, ContainerViewElement container, ViewElementBuilderContext builderContext) {
        container.find("entityForm", FormViewElement.class)
            .ifPresent(form -> form.setEncType(FormViewElement.ENCTYPE_MULTIPART));
    }
----

The last method we override is the handle our form submission.
We first check if there aren't any errors, then handle the fileUpload.

You can set your own feedback messages and use the https://across-docs.foreach.be/across-standard-modules/EntityModule/2.1.0.RELEASE/reference/#_entitylinkbuilder[EntityLinkBuilder] to generate
the right url's for redirection.

.FileUploadViewProcessor.java - Handle the submit
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
    @Override
    protected void doPost(EntityViewRequest entityViewRequest, EntityView entityView, EntityViewCommand command, BindingResult bindingResult) {
        if (!bindingResult.hasErrors()) {
            EntityViewContext entityViewContext = entityViewRequest.getEntityViewContext();

            FileRequest file = command.getExtension("upload", FileRequest.class);
            Advantage advantage = entityViewRequest.getEntityViewContext().getParentContext().getEntity(Advantage.class);
            MultipartFile[] files = file.getFiles();

            if (files != null && files.length > 0) {
                InputStream is = null;
                try {
                    is = files[0].getInputStream();

                    BufferedReader br = new BufferedReader(new InputStreamReader(is));
                    br.lines().forEach(line -> handleLineMethod(line)));
                } catch (IOException e) {
                    e.printStackTrace();
                }

                entityViewPageHelper.addGlobalFeedbackAfterRedirect(entityViewRequest, Style.SUCCESS,
                    "feedback.entityUpdated");

                if (entityViewRequest.hasPartialFragment()) {
                    entityView.setRedirectUrl(
                        UriComponentsBuilder.fromUriString(entityViewContext.getLinkBuilder().update(uniqueCodes))
                            .queryParam(WebTemplateInterceptor.PARTIAL_PARAMETER, entityViewRequest.getPartialFragment())
                            .toUriString()
                    );
                } else {
                    entityView.setRedirectUrl(entityViewContext.getLinkBuilder().overview());
                }

        }
    }
----


