:page-partial:
[[entity-query-infrastructure]]
= EntityQuery infrastructure
:sectnums:
:chapter-number: 0

EntityModule provides an abstraction layer for querying entities.
This abstraction is built around the concept of an `EntityQuery`.

This chapter gives some insight in the setup and how to customize if so wanted.

[[entity-query-executor]]
== EntityQueryExecutor
The `EntityQueryExecutor` is responsible for executing an `EntityQuery` and returning the entities requested.
An `EntityConfiguration` can have a single `EntityQueryExecutor.class` attribute holding the executor instance.

Default implementations exist for `JpaSpecificationExecutor` and `QueryDslPredicateExecutor`.
This means that any entity configurations having a repository of this type will get an `EntityQueryExecutor` created automatically.

> Since the `EntityQueryExecutor` is backed by a specific repository implementation, supported functionality also depends on the actual backing repository.

The presence of the `EntityQueryExecutor` is a requirement for the default <<entity-views,entity views>>.

=== AssociatedEntityQueryExecutor
Like `EntityQueryExecutor` that is registered on the `EntityConfiguration`, every `EntityAssociation` can have an `AssociatedEntityQueryExecutor` registered.
The `AssociatedEntityQueryExecutor` allows executing queries in the context of a single parent object.

Like the `EntityQueryExecutor`, the `AssociatedEntityQueryExecutor` is usually added automatically.

The presence of the `AssociatedEntityQueryExecutor` is a requirement for the default association <<entity-views,entity views>>.